### ISSUE TITLE
Add share buttons

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-web#153]
**Description**
We want users to share various pages/achievements, to 

- register referral 
- share interesting jobs
- inspire others
- share achievements/milestones; like getting hired or applying for a job

Share to:
- Facebook
- WhatsApp
- Twitter? (not sure what the usage looks like, I guess we could add it and then measure how often its used)

**Definition of done** 

Add the above mentioned share buttons to: 

- [ ] After user registration (_url_: app start page)
- [x] Job show page (_url_: job url)
- [ ] After applying to a job (_url_: job url)
- [ ] When receiving a job offer (_url: job url)
- [ ] After accepting a job offer (_url: job url)

**v2.0 / Future**

- [ ] Investigate if the share rate increase if we pre-fill some text, i.e "I got hired 🎉"
- [ ] First day of the job
- [ ] After finishing a job

---

This is a first draft so input/feedback/ideas are very welcome :)

**Comment by bex1** [comment]
Pre req #451

**Comment by Johanneseliasson93** [comment]
Archive?
